words=[
    "jenny",
    "apple",
    "beautiful",
    "mango",
    "jayanti",
    "ruthika",
    "attitude",
    "aeroplane",
    "blackboard",
    "car",
    "busstand"
    "Amusement",
    "Appeal",
    "Ambition",
    "Accept",
    "Sincerity",
    "Seek"
]
